version: '3.7'
services:

  ## User-Service Docker Compose Config
  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-database:5432/payscam-database
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres-database
    volumes:
      - ./user-service
    networks:
      - payscam-network

  ## Payment-Processing-Service Docker Compose Config
  payment-processing-service:
    container_name: payment-processing-service
    build:
      context: ./payment-processing-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-database:5432/payscam-database
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres-database
    volumes:
      - ./payment-processing-service
    networks:
      - payscam-network

  ## Payment-Processing-Service Docker Compose Config
  risk-management-service:
    container_name: risk-management-service
    build:
      context: ./risk-management-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-database:5432/payscam-database
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres-database
    volumes:
      - ./risk-management-service
    networks:
      - payscam-network

  ## React-app Docker Compose Config
  payscam-react:
    container_name: payscam-react
    build:
      context: ./payscam-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  ## Postgres Docker Compose Config
  postgres-database:
    container_name: postgres-database
    image: postgres:latest
    environment:
      POSTGRES_DB: payscam-database
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
    networks:
      - payscam-network

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - payscam-network
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - payscam-network

networks:
  payscam-network:
    driver: bridge

volumes:
  elasticsearch: