FROM openjdk:17
WORKDIR /
COPY ./target/risk-management-service-0.0.1-SNAPSHOT.jar risk-management-service-0.0.1-SNAPSHOT.jar
EXPOSE 8082
CMD ["java", "-jar", "risk-management-service-0.0.1-SNAPSHOT.jar"]