FROM openjdk:17
WORKDIR /
COPY ./target/payment-processing-service-0.0.1-SNAPSHOT.jar payment-processing-service-0.0.1-SNAPSHOT.jar
EXPOSE 8081
CMD ["java", "-jar", "payment-processing-service-0.0.1-SNAPSHOT.jar"]