### Get user account
GET http://localhost:8081/api/payment/user_account/101

### Increase user's balance
POST http://localhost:8081/api/payment/user_account/add
Content-Type: application/json

{
  "account": "101",
  "amount": 150.99
}

### Decrease user's balance
POST http://localhost:8081/api/payment/user_account/subtract
Content-Type: application/json

{
  "account": "101",
  "amount": 150.99
}

### Create new payment
POST http://localhost:8081/api/payment/add
Content-Type: application/json

{
  "fromAccount": "102",
  "toAccount": "101",
  "amount": 110.5,
  "isInternal": true
}

### Get user payments
GET http://localhost:8081/api/payment/user_payments/101
